{% set name = "saqc" %}
{% set version = "2.7.0.post3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e37ae529ba40a939032e5f080899df13f5bf75b9acf41c44aace31e10b30fcd6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0
  entry_points:
    - saqc = saqc.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer ==0.29
  run:
    - python >={{ python_min }}
    - click =8.2.1
    - docstring_parser ==0.17
    - fancy-collections =0.3.0
    - fastdtw =0.3.4
    - matplotlib-base =3.10.6
    - numpy =2.2.6
    - outlier-utils ==0.0.5
    - pyarrow =21.0.0
    - pandas =2.3.2
    - scikit-learn =1.7.1
    - scipy =1.14.1
    - typing_extensions =4.15.0
    - pydantic =2.11.7
    - eval-type-backport =0.2.2
    - xorg-libx11
test:
  requires:
    - python {{ python_min }}
  imports:
    - saqc
  commands:
    - saqc --help


about:
  home: https://git.ufz.de/rdm-software/saqc
  summary: 'SaQC: System for automated Quality Control'
  description: |
    Anomalies and errors are the rule not the exception when working with time
    series data. This is especially true, if such data originates from in-situ
    measurements of environmental properties.  Almost all applications, however,
    implicily rely on data, that complies with some definition of 'correct'.  In
    order to infer reliable data products and tools, there is no alternative to
    quality control. SaQC provides all the building blocks to comfortably bridge
    the gap between 'usually faulty' and 'expected to be corrected' in a
    accessible, consistent, objective and reproducible way.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  doc_url: https://rdm-software.pages.ufz.de/saqc/index.html
  dev_url: https://git.ufz.de/rdm-software/saqc/

extra:
  recipe-maintainers:
    - schaefed
    - bernt-matthias
