{% set name = "saqc" %}
{% set version = "2.7.0.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b186ae0434bf47ab8f0e06a6be0e91d0709951bf3c04e53ea67e03132b8de0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --ignore-installed
  number: 0
  entry_points:
    - saqc = saqc.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer ==0.29
  run:
    - python >={{ python_min }}
    - click =8.1.7
    - docstring_parser 0.16
    - fancy-collections =0.3.0
    - fastdtw =0.3.4
    - matplotlib-base =3.8.3
    - numpy =1.26.4
    - outlier-utils ==0.0.5
    - pyarrow =15.0.2
    - pandas =2.2.1
    - scikit-learn =1.4.1
    - scipy =1.12.0
    - typing_extensions =4.10.0
    - xorg-libx11

test:
  requires:
    - python {{ python_min }}
  imports:
    - saqc
  commands:
    - saqc --help


about:
  home: https://git.ufz.de/rdm-software/saqc
  summary: 'SaQC: System for automated Quality Control'
  description: |
    Anomalies and errors are the rule not the exception when working with time
    series data. This is especially true, if such data originates from in-situ
    measurements of environmental properties.  Almost all applications, however,
    implicily rely on data, that complies with some definition of 'correct'.  In
    order to infer reliable data products and tools, there is no alternative to
    quality control. SaQC provides all the building blocks to comfortably bridge
    the gap between 'usually faulty' and 'expected to be corrected' in a
    accessible, consistent, objective and reproducible way.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  doc_url: https://rdm-software.pages.ufz.de/saqc/index.html
  dev_url: https://git.ufz.de/rdm-software/saqc/

extra:
  recipe-maintainers:
    - schaefed
    - bernt-matthias
